# As YAML Configuration File
http:
  routers:
    router-grafana:
      entrypoints:
        - "https"
      service: grafana-service
      rule: "Host(`grafana.access.devilsan.com`)"
      middlewares:
        - hsts
        - redirect
        - scheme
      tls:
        certResolver: linodev4
        domains:
          - main: grafana.access.devilsan.com

  services:
    grafana-service:
      loadBalancer:
        healthCheck:
          interval: "5s"
          timeout: "3s"
        servers:
          - url: "http://192.168.1.10:3000"
        passHostHeader: true