---
- name: download node exporter
  vars:
    node_hosts:
      x86_64:
        archi: amd64
      aarch64:
        archi: arm64
      armv6l:
        archi: armv6
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{node_hosts[ansible_architecture]['archi']}}.tar.gz
    dest: /tmp

- name: unarchive node exporter
  vars:
    node_hosts:
      x86_64:
        archi: amd64
      aarch64:
        archi: arm64
      armv6l:
        archi: armv6
  unarchive:
    remote_src: yes
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{node_hosts[ansible_architecture]['archi']}}.tar.gz
    dest: /tmp

- name: move node exporter to /usr/local/bin
  vars:
    node_hosts:
      x86_64:
        archi: amd64
      aarch64:
        archi: arm64
      armv6l:
        archi: armv6
  copy:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{node_hosts[ansible_architecture]['archi']}}/node_exporter
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    owner: root
    group: root
    mode: 0755

- name: remove repo.
  vars:
    node_hosts:
      x86_64:
        archi: amd64
      aarch64:
        archi: arm64
      armv6l:
        archi: armv6
  file:
    state: absent
    path: /tmp/node_exporter-{{ node_exporter_version }}.linux-{{node_hosts[ansible_architecture]['archi']}}

- name: install unit file to systemd
  template:
    src: templates/node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0600

- name: configure systemd to use service
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: node_exporter.service
