---
- name: Create haproxy yaml config file.
  tags: ["haproxy", "never"]
  when: inventory_hostname == 'proxy'
  template:
    src: haproxy.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Haproxy Systemd service reload
  tags: ["haproxy", "never"]
  when: inventory_hostname == 'proxy'
  become: yes
  ansible.builtin.systemd:
    name: haproxy.service
    enabled: yes
    state: reloaded