---
- hosts: localhost
  vars_files:
    - "{{playbook_dir}}/vars.yml"
    - repo-pass.yml

  tasks:
    - name: clone a repo
      tags:
         - always
         - printa
      git:
        repo: "https://sanfx:{{lookup('env', 'GITHUB_TOKEN')}}@github.com/sanfx/vault.git"
        dest: "{{config_dir}}"
        depth: 1

    - name: print info
      tags: ["always", "printa", "config"]
      debug:
        msg:
          - "{{config_dir}}"

- hosts: localhost
  tags: ["never", "laptop"]
  gather_facts: true
  become: true
  become_method: sudo
  ignore_errors: yes
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  tasks:
    - include_vars: "{{config_dir}}/config.yml"
    - import_role:
        name: node_exporter
  
- hosts: local
  tags: ["never", "local"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - include_vars: "{{config_dir}}/config.yml"
    - import_role:
        name: node_exporter
    - import_role:
        name: pihole
    - import_role:
        name: traefik
    - import_role:
        name: monitor
    - import_role:
        name: keepalived
    - import_role:
        name: prometheus

- hosts: low_profile
  tags: ["never", "low"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - include_vars: "{{config_dir}}/config.yml"
    - import_role:
        name: node_exporter
    
- hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  tasks:
    - name: clean this repo.
      file:
        state: absent
        path: "{{config_dir}}"
      tags:
        - always
        - printa
        - repo-clean
