---
- name: Verify traefik stacks directory exists.
  tags: ["traefik", "never"]
  file:
    path: "/home/{{ansible_user}}/stacks/traefik/letsencrypt"
    state: directory

- name: Copy traefik static with owner and permissions
  tags: ["traefik", "never"]
  when: inventory_hostname == 'rockpix'
  template:
    src: static_traefik.yml.j2
    dest: /home/{{ansible_user}}/stacks/traefik/static/traefik.yml
    mode: 0775

- name: Copy traefik dynamic with owner and permissions
  tags: ["config", "never"]
  when: inventory_hostname == 'rockpix'
  ansible.builtin.copy:
    src: ./config
    dest: /home/{{ansible_user}}/stacks/traefik/
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
    mode: '0644'

- name: Generate admin password hash
  shell: echo $(htpasswd -nb {{traefik_admin_user}} {{traefik_admin_password}}) | sed -e s/\\$/\\$\\$/g
  tags: ["traefik", "never"]
  when: inventory_hostname == 'proxy'
  register: traefikpassword

- name: Create docker-compose stack file.
  tags: ["traefik", "never"]
  when: inventory_hostname == 'proxy'
  template:
    src: docker-compose.j2
    dest: /home/{{ansible_user}}/stacks/traefik/docker-compose.yml
    mode: 0775

- name: create traefik and access log files.
  file:
      path: "{{ item }}"
      state: touch
  with_items:
    - "/var/log/traefik.log"
    - "/var/log/access.log"
  become: true
  tags: ["traefik", "never"]
  when: inventory_hostname == 'rockpix'
  become_method: sudo
  ignore_errors: true

- name: Deploy Traefik Reverse Proxy stack from a compose file (from {{inventory_hostname}})
  tags: ["never", "traefik"]
  when: "inventory_hostname == 'proxy'"
  ignore_errors: true
  docker_stack:
    state: present
    name: traefik
    compose:
      - /home/{{ansible_user}}/stacks/traefik/docker-compose.yml