---
  - name: Verify stacks/home-assistant and its config directory exists
    when: inventory_hostname == 'rockpix'
    tags: ["ha", "never"]
    file:
      path: "/home/{{ansible_user}}/stacks/home-assistant/config"
      state: directory

  - name: Create configuration file for Home Assistant.
    when: inventory_hostname == 'rockpix'
    tags: ["ha", "never"]
    template:
      src: configuration.yml.j2
      dest: /home/{{ansible_user}}/stacks/home-assistant/config/configuration.yaml
      mode: 0775

  - name: Create Home Assistant docker-compose stack file.
    when: inventory_hostname == 'rockpix'
    tags: ["ha", "never"]
    template:
      src: ha-docker-compose.yml.j2
      dest: /home/{{ansible_user}}/stacks/home-assistant/docker-compose.yml
      mode: 0775

  - name: Home Assistant Docker Compose Systemd Service file creation
    when: inventory_hostname == 'rockpix'
    tags:  ["ha", "never"]
    copy:
      dest: /etc/systemd/system/home-assistant-docker-compose.service
      content: |
        [Unit]
        Description=Docker Compose Service for Home Assistant.
        Requires=docker.service
        After=docker.service
        [Service]
        Type=oneshot
        RemainAfterExit=true
        WorkingDirectory=/home/{{ansible_user}}/stacks/home-assistant/
        ExecStart=/usr/local/bin/docker-compose up -d --remove-orphans
        ExecStop=/usr/local/bin/docker-compose down
        [Install]
        WantedBy=multi-user.target

  - name: forcing systemd to re-execute itself (2.8 and above)
    when: inventory_hostname == 'rockpix'
    tags: ["ha", "never"]
    ansible.builtin.systemd:
      daemon_reexec: yes

  - name: Home assistant docker-compose Systemd service activation
    when: inventory_hostname == 'rockpix'
    tags: ["ha", "never"]
    ansible.builtin.systemd:
      name: home-assistant-docker-compose.service
      enabled: yes
      state: started
