---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  skumar:
    displayname: "Sanjeev Kumar"
    # Password is Authelia
    password: {{authelia_user_password}}
    email: {{authelia_user_email}}
    groups:
      - admins
      - dev
...