http:
  middlewares:

    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.access.devilsan.com"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"

    rate-limit:
      rateLimit:
        average: 100
        burst: 50

    compress:
      compress: {}

    sonarr-dark:
      plugin:
        traefik-themepark:
          app: sonarr
          theme: dark
    pihole-aquamarine:
      plugin:
        traefik-themepark:
          app: pihole
          theme: dark
    hsts:
      headers:
        frameDeny: true
        browserXssFilter: true
        stsIncludeSubdomains: true
        forceSTSHeader: true
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        stsPreload: true
        stsSeconds: 63072000
        sslRedirect: true
        customFrameOptionsValue: "SAMEORIGIN"
        referrerPolicy: "same-origin"
        permissionsPolicy: "autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), microphone=(), midi=(), navigation-override=(self), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(self), clipboard-write=(self), speaker-selection=()"
        accessControlAllowMethods:
          - GET
          - POST
          - OPTIONS
          - PUT
        accessControlAllowOriginList:
          - https://access.devilsan.com
          - https://devilsan.com
        contentTypeNosniff: true
        sslForceHost: true

    redirect:
      redirectScheme:
        permanent: true
        scheme: https

    scheme:
      headers:
        customRequestHeaders:
          X-Scheme: https
    stripper:
      stripPrefix:
        prefixes:
          - "/rockpix"
          - "/rockpi"
        forceSlash: true
