# As YAML Configuration File
http:
  routers:
    router-prometheus:
      entrypoints:
        - "https"
      service: prometheus-https-service
      rule: "Host(`prometheus.access.devilsan.com`)"
      middlewares:
        - chain-authelia
      tls:
        certResolver: linodev4
        domains:
          - main: prometheus.access.devilsan.com

  services:
    prometheus-https-service:
      loadBalancer:
        healthCheck:
          interval: "5s"
          timeout: "3s"
        servers:
          - url: "http://100.71.28.98:9191"
        passHostHeader: true