# As YAML Configuration File
http:
  routers:
    router1:
      entrypoints:
        - "web"
      service: dnsmasq-service
      rule: "Host(`dnsmasq.home.local`)"

  services:
    dnsmasq-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.200:8085"
          - url: "http://192.168.1.201:8085"