# As YAML Configuration File
http:
  routers:
    router-pix-minio:
      entrypoints:
        - "web"
      service: pix-minio-service
      rule: "Host(`pix.minio.home.local`)"

  services:
    pix-minio-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.11:9000"