# As YAML Configuration File
http:
  routers:
    router-apache2:
      entryPoints:
        - "https"
      service: web-service
      rule: "Host(`access.devilsan.com`)"
      middlewares:
        - hsts
        - redirect
        - scheme
      tls:
        certResolver: linodev4
        domains:
          - main: access.devilsan.com

  services:
    web-service:
      loadBalancer:
        healthCheck:
          interval: "5s"
          timeout: "3s"
        servers:
          - url: "http://100.71.28.98:80"
          - url: "http://192.168.1.10:80"
          # - url: "http://192.168.1.11:8085"
        passHostHeader: true
