---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{playbook_dir}}/vars.yml"
    - repo-pass.yml
  tasks:
    - name: clone a repo
      tags:
         - always
         - printa
      git:
        repo: "https://sanfx:{{lookup('env', 'GITHUB_TOKEN')}}@github.com/sanfx/vault.git"
        dest: "{{config_dir}}"
        depth: 1

    - name: print info
      tags: ["always", "print", "config"]
      debug:
        msg:
          - "{{config_dir}}"

- hosts: all
  tags: ["never", "all"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
      - block:
        - include_vars: "{{config_dir}}/config.yml"
        - include_vars: "{{config_dir}}/nextcloud.yml"
        - import_role:
            name: host-defaults
        rescue:
          - set_fact:
              role_failed: true

- hosts: swarm_managers
  tags: ["vms", "never"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
        - include_vars: "{{config_dir}}/config.yml"
        - import_role:
            name: docker
        - import_role:
            name: swarm-managers
      rescue:
        - set_fact:
            role_failed: true

- hosts: swarm_managers
  tags: ["vms", "never"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
      - include_vars: "{{config_dir}}/config.yml"
      - import_role:
          name: swarm-managers
      - import_role:
          name: dns_stack
      - import_role:
          name: dashboards
      - import_role:
          name: cluster_manage
      - import_role:
          name: monitor
      - import_role:
          name: traefik
      rescue:
        - set_fact:
            role_failed: true

- hosts: swarm_workers
  tags: ["vms", "never"]
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
        - include_vars: "{{config_dir}}/config.yml"
        - import_role:
            name: docker
        - import_role:
            name: swarm-workers
      rescue:
        - set_fact:
            role_failed: true

- hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  tasks:
    - name: clean this repo.
      file:
        state: absent
        path: "{{config_dir}}"
      tags:
        - always
        - repo-clean
