---    
  - name: copy keepalived configuration 
    tags: ["keepalived", "config", "never"]
    become: yes
    vars:
      ka_hosts:
        rockpi:
          state: keepalived_master.j2
        rockpix:
          state: keepalived_backup.j2
    template:
      src: "{{ ka_hosts[inventory_hostname]['state'] }}"
      dest: /etc/keepalived/keepalived.conf


  - name: Systemd service activation
    tags: ["keepalived", "never"]
    become: yes
    ansible.builtin.systemd:
      name: keepalived.service
      enabled: yes
      state: reloaded


