---
- hosts: localhost
  become: yes
  become_method: sudo

  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present

  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add sudoers users to wheel group
    user:
      name=ansible
      groups=wheel
      append=yes
      state=present
      createhome=yes

  - name: Add sudoers users to vagrant group
    user:
      name=ansible
      groups=vagrant
      append=yes
      state=present
      createhome=yes

  - name: Make sure we have a 'mysql' group
    group:
      name: mysql
      gid: 132
      state: present

  - name: Add mysql user and group
    user:
      name: mysql
      group: mysql
      uid: 132
      state: present
      createhome: no

  - name: Set up authorized keys for the ansible user
    authorized_key: user=ansible key="{{item}}"
    with_file:
      - ./.ssh/id_rsa.pub

  - name: Disable the systemd-resolve stub DNS resolver (replaced by unbound)..
    lineinfile:
      dest: /etc/systemd/resolved.conf
      regexp: '^#DNSStubListener='
      line: 'DNSStubListener=no'
      state: present
    notify:
      - restart systemd-resolved
  
  - name: Remove symlink /etc/resolv.conf
    file:
      path: "/etc/resolv.conf"
      state: absent

  - name: Touch resolv.conf file, but do not change times this makes the task idempotent
    ansible.builtin.file:
      path: /etc/resolv.conf
      state: touch
      mode: u+rw,g-wx,o-rwx
      modification_time: preserve
      access_time: preserve

  - name: Update nameserver in /etc/resolv.conf
    lineinfile:
      path: /etc/resolv.conf
      state: present
      line: 'nameserver 1.1.1.1'
      insertbefore: BOF

  - name: finding python version
    shell: python3 --version
    register: pv

  - name: print result
    debug:
      msg:
        - "{{pv}}"

  - name: Systemd dnsmasq service de-activation
    tags: ["dns"]
    systemd:
      name: dnsmasq.service
      enabled: no
      state: stopped
