---
- hosts: localhost
  gather_facts: false
  vars_files:
    - "{{playbook_dir}}/vars.yml"
    - repo-pass.yml
  tasks:
    - name: clone a repo
      git:
        repo: "https://sanfx:{{lookup('env', 'GITHUB_TOKEN')}}@github.com/sanfx/vault.git"
        dest: "{{config_dir}}"

- hosts: all
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
        - include_vars: "{{config_dir}}/config.yml"
        - include_vars: "{{config_dir}}/nextcloud.yml"
        - import_role:
            name: host-defaults
        - import_role:
            name: nextcloud
      rescue:
        - set_fact:
            role_failed: true

  # handlers:
  #   - name: restart systemd-resolved
  #     service:
  #       name: systemd-resolved
  #       state: restarted
  #     when: reboot_required.stat.exists == false

- hosts: swarm_managers
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
        - include_vars: "{{config_dir}}/config.yml"
        - import_role:
            name: docker
        - import_role:
            name: swarm-managers
      rescue:
        - set_fact:
            role_failed: true

- hosts: swarm_managers
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    # - block:
    - include_vars: "{{config_dir}}/config.yml"
    - import_role:
        name: swarm-managers
    - import_role:
        name: dns_stack
    - import_role:
        name: dashboards
    - import_role:
        name: cluster_manage
    # - import_role:
    #     name: backups
    - import_role:
        name: monitor
    - import_role:
        name: traefik

      # rescue:
      #   - set_fact:
      #       role_failed: true

- hosts: swarm_workers
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - block:
        - include_vars: "{{config_dir}}/config.yml"
        - import_role:
            name: docker
        - import_role:
            name: swarm-workers
      rescue:
        - set_fact:
            role_failed: true

- hosts: local
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - include_vars: "/home/sanjeev/ansible/vault/config.yml"
    - import_role:
        name: traefik
    - import_role:
        name: dns_stack
    - import_role:
        name: monitor
    - import_role:
        name: keepalived

- hosts: remote
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  become: yes
  tasks:
    - import_role:
        name: dns_stack
      
- hosts: localhost
  gather_facts: false
  run_once: true
  vars_files:
    - "{{playbook_dir}}/vars.yml"
  tasks:
    - name: clean this repo.
      file:
        state: absent
        path: "{{config_dir}}"
      tags:
        - always
        - repo-clean
